backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: ezriharmusial/LastMessengerS
  # branch: main
  # base_url: 'https://lastmessengers.artkidsfoundation.org'
  # auth_endpoint: 'api/admin/auth'
# Local testing
local_backend: true
collections:
  - name: artists
    label: LastMessengerS
    label_singular: 'Artist'
    folder: src/lib/md-collections/artists
    create: true
    identifier_field: "stage_name"
    fields:
      - name: nav_label
        required: false
      - {label: "Profile Picture", name: "image", widget: "image", required: false, media_folder: "/static/uploads/artists", public_folder: "/uploads/artists" }
      - name: active
        label: "LastMessenger Status"
        widget: boolean
        default: true
      - name: stage_name
      - name: name
        default: Unknown


      - label: "Music Genres"
        name: "genres"
        widget: "relation"
        collection: "genres"
        value_field: "title"
        search_fields: ["title", "description"]
        multiple: true
        required: false


      - name: body
        label: Biography
        required: false
        widget: markdown
      - label: "Album Track"
        name: "Discography"
        widget: "relation"
        collection: "media"
        value_field: "title"
        search_fields: ["title", "artist", "featuring_artist", "producer", "lyrics" ]
        multiple: false
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: media
    label: "Album Tracks"
    label_singular: 'Track'
    folder: src/lib/md-collections/media
    sortable_fields: ['order', 'title']
    create: true
    # adding a nested object will show the collection folder structure
    fields:
      - name: nav_label
        label: "URL Slug"
        required: false

      - label: "Media File"
        name: "media_file"
        widget: "file"
        media_folder: "/static/uploads/media"
        public_folder: "/uploads/media"

      - {label: "Track Coverimage", name: "image", widget: "image", required: false, media_folder: "/static/uploads/coverimages", public_folder: "/uploads/coverimages"}

      - name: title
        label: "Track Title"

      - label: "Track Artist"
        name: "artist"
        widget: "relation"
        collection: "artists"
        value_field: "stage_name"
        search_fields: ["stage_name", "name"]

      - label: "Featuring Artists"
        name: "featuring"
        widget: "relation"
        collection: "artists"
        value_field: "stage_name"
        search_fields: ["stage_name", "name"]
        multiple: true
        required: false

      - label: "Producer"
        name: "producer"
        widget: "relation"
        collection: "artists"
        value_field: "stage_name"
        search_fields: ["stage_name", "name"]
        multiple: true
        required: false

      - label: "Release Album"
        name: "release_album"
        widget: "relation"
        collection: "albums"
        value_field: "title"
        search_fields: ["title", "description"]
        multiple: true
        required: false

      - name: order
        label: "Track Number"
        widget: number
        value: int
        min: 1
        required: true

      - label: "Release Year"
        name: "date"
        widget: "datetime"
        required: false

      - label: "Music Genres"
        name: "genres"
        widget: "relation"
        collection: "genres"
        value_field: "title"
        search_fields: ["title", "description"]
        multiple: true
        required: false

      - name: quote
        required: false
      - name: excerpt
        required: false
      - name: body
        label: Lyrics
        required: false
        widget: markdown
      - name: aditional_credits
        widget: markdown
        required: false

    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: albums
    label: Unity Albums
    label_singular: 'Album'
    folder: src/lib/md-collections/albums
    create: true
    # adding a nested object will show the collection folder structure
    fields:
      - name: nav_label
        required: false
      - {label: "Album Cover", name: "image", widget: "image", required: false, media_folder: "/static/uploads/albumcovers", public_folder: "/uploads/albumcovers"}
      - name: title
      - label: "Release Year"
        name: "date"
        widget: "datetime"
        required: false

      - label: "Album Tracklist"
        name: "tracklist"
        widget: "relation"
        collection: "media"
        value_field: "title"
        search_fields: ["title", "artist", "featuring_artist", "producer", "lyrics" ]
        multiple: true

      - label: "Music Genres"
        name: "genres"
        widget: "relation"
        collection: "genres"
        value_field: "title"
        search_fields: ["title", "description"]
        multiple: true
        required: false

      - name: credits
        required: false
      - name: body
        label: "Album Info"
        widget: markdown
        required: false
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
  - name: genres
    label: Music Genres
    label_singular: 'Genre'
    folder: src/lib/md-collections/genres
    create: true
    # adding a nested object will show the collection folder structure
    fields:
      - name: title
      - name: body
        label: Description
        widget: markdown
        required: false

media_folder: "static/uploads"
public_folder: "/uploads"
search: true
show_preview_links: true
publish_mode: editorial_workflow

# media_library:
#   name: cloudinary
#   config:
#     cloud_name: artkids-foundation
#     api_key: 263829663159721

site_url: https://lastmessengers.artkidsfoundation.org
display_url: https://lastmessengers.artkidsfoundation.org
logo_url: https://lastmessengers.artkidsfoundation.org/images/LMS_web-logo_small_light.png